name: dogedevice
description: "A new Flutter project."
version: 0.0.4

environment:
  sdk: ">=3.6.1 <4.0.0"
  flutter: 3.27.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  device_info_plus: ^11.2.1
  windows_system_info: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
