name: build-all

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PUBSPEC: "pubspec.yaml"

permissions:
  contents: write

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/build-test.yml"
      - ".github/workflows/build.yml"

jobs:
  pre:
    runs-on: ubuntu-24.04
    outputs:
      pubspec: ${{ env.PUBSPEC }}
      target: ${{ env.TARGET }}
    steps:
      - run: echo "Bypass GitHub Action Restriction"

  build-all:
    needs:
      - pre
    strategy:
      matrix:
        target: [ios, android, macos, linux, web, windows]
        include:
          - target: macos
            platform: macos-latest
            build-args: "build macos --release"
          - target: ios
            platform: macos-latest
            build-args: "build ios --release --no-codesign"
          - target: android
            platform: ubuntu-24.04
            build-args: "build apk --release"
          - target: linux
            platform: ubuntu-20.04
            build-args: "build linux --release"
          - target: web
            platform: ubuntu-20.04
            build-args: "build web --release"
          - target: windows
            platform: windows-2019
            build-args: "build windows --release"
    uses: ./.github/workflows/build.yml
    with:
      path: ${{ needs.pre.outputs.pubspec }}
      target: ${{ matrix.target }}
      build-args: ${{ matrix.build-args }}
      platform: ${{ matrix.platform }}