name: create-tag

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_call:
    inputs:
      version:
        default: '0'
        required: true
        type: string
    outputs:
      tag:
        description: "Pushed tag version"
        value: ${{ jobs.create-tag.outputs.tag }}

jobs:
  create-tag:
    runs-on: ubuntu-24.04
    outputs:
      tag: ${{ steps.push.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - 
        id: push
        run: |
          version="${{ inputs.version }}"
          git tag $version && git push --tags
          echo tag=$version >> $GITHUB_OUTPUT
        name: Push Tag
        shell: bash
